### ISSUE TITLE
Components' names 🧐

### ISSUE THREAD

**Issue by joaoviana** [FACxBeamery/tom-project-week-6#14]
was wondering if SecondCity, FirstCity and LastCity would be the adequate names for what these components do. 
you have been dealing with the `stage` prop throughout the app. could you find a way to have just one component called City.js ? 

G00D LuCKKK!

**Comment by thomas-galligan** [comment]
I agree, I've renamed SecondCity to MiddleCity (as it is rendered on the middle 3 stages of the app). I have kept the components separate as they render different things, and to me this seems more logical.
