### ISSUE TITLE
Please leave documentation about your app and how to run it locally before code review

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/tom-project-week-6#3]
Please leave clear documentation on your repo to explain what your project does and how it can be installed and run locally, so that your code reviewers can do this. Include instructions on what API keys or tokens are needed and how to include them. You might also share the API key to the Slack channel to help out your code reviewers.

**Comment by thomas-galligan** [comment]
Thanks for the advice, I'll amend the README prior to code review. I'll also share an API key in the slack channel so that reviewers don't have to worry about environment variables.
