### ISSUE TITLE
After already finishing and submitting the form, text input is not cleared

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tom-project-week-6#4]
Cool! I played the game! Good stuff.

My problem is that when I go back and play again, the text input for the city field is still populated with my last input!

![Screen Shot 2019-10-18 at 09 24 36](https://user-images.githubusercontent.com/37771591/67078521-62af9b00-f189-11e9-824f-41c42bd477dd.png)

**Comment by thomas-galligan** [comment]
This is fixed now
