### ISSUE TITLE
Input for city needs validation to deal with non-existent cities

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tom-project-week-6#6]
![Screen Shot 2019-10-18 at 09 31 11](https://user-images.githubusercontent.com/37771591/67078903-20d32480-f18a-11e9-9217-5dcede571eac.png)

Wow, I didn't know that 'adfadfadfdfa' was a city! 😁

**Comment by thomas-galligan** [comment]
Thank you! I've stuck in some validation for this so it's working now.
