### ISSUE TITLE
Clean up CSS in project architecture

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tom-project-week-6#7]
At the moment, there is CSS spread across different files and different folders. Can this be cleaned up? 

![Screen Shot 2019-10-18 at 09 36 49](https://user-images.githubusercontent.com/37771591/67079372-fb92e600-f18a-11e9-84ae-a4aba85cae87.png)

**Comment by thomas-galligan** [comment]
index.css has been moved into src/css/
