### ISSUE TITLE
Test is broken!

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tom-project-week-6#8]
![Screen Shot 2019-10-18 at 09 41 49](https://user-images.githubusercontent.com/37771591/67079688-8d025800-f18b-11e9-9178-de99a0c4e881.png)

It looks like it is simply an incorrect path name!

**Comment by thomas-galligan** [comment]
You were right - I didn't updated the path to App.js after restructuring my file system. This is fixed now.
